import property1 from 'src/assets/property1.jpeg'
import property2 from 'src/assets/property2.jpeg'
import property3 from 'src/assets/property3.jpeg'
import property4 from 'src/assets/property4.jpeg'

export const listings = [
	{
		id: 0,
		type: 'Maison',
		operation: 'vendre',
		roomsNum: 3,
		surface: 230,
		price: '1,110,122',
		location: 'Marrakech, Ennakhil (Palmeraie)',
		createdBy: 'MARRAKECH CONSEILS INVEST',
		image: property1,
		dateAdded: '3',
		liked: true,
	},
	{
		id: 1,
		type: 'Appartement',
		operation: 'vendre',
		roomsNum: 2,
		surface: 140,
		price: '1,000,122',
		location: 'Marrakech Guéliz',
		createdBy: 'MARRAKECH CONSEILS INVEST',
		image: property2,
		dateAdded: '5',
		liked: false,
	},
	{
		id: 2,
		type: 'Maison',
		operation: 'vendre',
		roomsNum: 3,
		surface: 230,
		price: '1,110,122',
		location: 'Marrakech, Ennakhil (Palmeraie)',
		createdBy: 'MARRAKECH CONSEILS INVEST',
		image: property3,
		dateAdded: '3',
		liked: false,
	},
	{
		id: 3,
		type: 'Maison',
		operation: 'vendre',
		roomsNum: 3,
		surface: 230,
		price: '1,110,122',
		location: 'Marrakech, Ennakhil (Palmeraie)',
		createdBy: 'MARRAKECH CONSEILS INVEST',
		image: property4,
		dateAdded: '5',
		liked: true,
	},
	{
		id: 4,
		type: 'Maison',
		operation: 'vendre',
		roomsNum: 3,
		surface: 230,
		price: '1,110,122',
		location: 'Marrakech, Ennakhil (Palmeraie)',
		createdBy: 'MARRAKECH CONSEILS INVEST',
		image: property1,
		dateAdded: '3',
		liked: false,
	},
	{
		id: 5,
		type: 'Maison',
		operation: 'vendre',
		roomsNum: 3,
		surface: 230,
		price: '1,110,122',
		location: 'Marrakech, Ennakhil (Palmeraie)',
		createdBy: 'MARRAKECH CONSEILS INVEST',
		image: property1,
		dateAdded: '3',
		liked: false,
	},
]